### ISSUE TITLE
External input element with picker

### ISSUE THREAD

**Issue by ulismuli** [mskocik/svelty-picker#103]
I noticed that it is possible to specify the input element by using the parameter "inputElement". However it is not (yet?) documented. I tried using an external text element but it didn't work.
Click on the input element did not open the picker popup.
Is this a supported feature or currently under development? I would like to use this in order to specify custom input elements like a text element e.g. with configured width.

**Comment by mskocik** [comment]
It's not documented, because it's designed to be used internally for custom element version I personally use.

In planned v4 it will be slightly changed (changes already in v4 branch). I have never tried to pass custom input element in svelte, but I would say, it should work. 

Will check it out when I get back feom holidays

**Comment by mskocik** [comment]
Here is an [example](https://svelte.dev/repl/aea0392fdd034a67b053ffc479575882?version=4.0.5) how to use it

**Comment by mskocik** [comment]
Check out customizable slots in v4. Should be flexible enough.
