### ISSUE TITLE
Changing default style is not working 

### ISSUE THREAD

**Issue by mugu-fatman** [mskocik/svelty-picker#129]
Hi,
Thanks for this awesome datepicker svelte component 
I tried to change the styling of Today and Clear button but seems its not working, I tried to test it using Svelte REPL. Also it would be nice to know if I can set the height, width and font for the component

Thanks

**Comment by mskocik** [comment]
You can change colors for buttons by CSS properties. For today it's `--sdt-primary` and `--sdt-today-bg` on hover. Check the documentation page "theme" where is list of all available properties.

Font is changeable and inherited from your page.

You can change width by using `:global()` overrides.

Changing height is not recommended due to transition in "Year" view, which use hardcoded values. But I haven't tested it. But component doesn't offer any built-in way to customize it's height.

**Comment by mugu-fatman** [comment]
Thanks for your reply , probably just want to make sure so the height of this input field cannot be changed ? 
![image](https://github.com/mskocik/svelty-picker/assets/62667193/fd82ebd9-649b-4679-9f24-c1b89b844d09)

**Comment by mugu-fatman** [comment]
Thanks for your answer, I could change the styles and fonts
