### ISSUE TITLE
Goto next month issue on 31st

### ISSUE THREAD

**Issue by zac-robinson** [mskocik/svelty-picker#146]
When on the 31st of a month, (31/10 for example) if you click the jump to next month button in the calendar then you get moved 2 month into the future (December).

Replicated on the docs page: https://mskocik.github.io/svelty-picker/

Only seems to happen on initial load, if you navigate back to October and select the 31st, then click next month you are taken to November as expected

**Comment by garikAsplund** [comment]
This looks like a simple fix--the issue comes from adding a month via the Date object in JS. If the next month doesn't have as many days, then it rolls over to the following month. This'll happen, too, if you select January 29 and hit 'next' as February only has 28 days.

I'll see if my quick patch is enough for a pull request or if it messes up a variable elsewhere. First time laying eyes on this so don't really know for sure.

**Comment by mskocik** [comment]
@garikAsplund your PR was good, I just added fix for keyboard navigation as well. Thanks for help.
