### ISSUE TITLE
"Today" and "Cancel" button not dissapearing

### ISSUE THREAD

**Issue by maugenst** [mskocik/svelty-picker#150]
Having this Picker on the page:
`<SveltyPicker pickerOnly initialDate="{new Date()}" bind:value={date} on:input={addDate} mode="datetime" autocommit=true todayBtn=false clearBtn=false format="dd.MM.yyyy HH:mm"/>
`

Should remove the Today and the Cancel button, but it still appears:

<img width="279" alt="image" src="https://github.com/mskocik/svelty-picker/assets/6390135/fd042cb1-fefa-46c5-b90a-84cf2d6f63d2">

Any advice?

**Comment by mskocik** [comment]
You need to wrap bool value in parenthesis like this `todayBtn={false}`, otherwise it's being passed as `string`.

**Comment by maugenst** [comment]
Nice ... Works like a charm. Would it be possible to give an example in the docs?

An another question: Can I set the default format to 24h?

**Comment by mskocik** [comment]
> Nice ... Works like a charm. Would it be possible to give an example in the docs?

Not sure, where to put it, because this is "svelte" stuff, not something library-specific.

> An another question: Can I set the default format to 24h?

Sure, you can check the all available format settings when you expand this `<details>` element. Probably it's not that obvious, especially when tailwind resets the mouse cursor 🤔 

![image](https://github.com/mskocik/svelty-picker/assets/25513620/6b260df7-843b-4114-a015-3d47e54d5e0b)

**Comment by maugenst** [comment]
Thank you very much! Kudos to you for responding so fast!
