### ISSUE TITLE
Selecting same date clears input

### ISSUE THREAD

**Issue by Roger-Sa** [mskocik/svelty-picker#25]
When using date only and a date is already selected, selecting the same date again will clear the input. Basically it deselects already selected date, which seems weird to me. 

This part of the code seems to indicate that it is intentional:
```
function onDate(e) {
    let setter = e.detail || null;
    if (e.detail && innerDate) {
      if (innerDate.getUTCFullYear() === e.detail.getUTCFullYear()
       && innerDate.getUTCMonth() === e.detail.getUTCMonth()
       && innerDate.getUTCDate() === e.detail.getUTCDate()
       && resolvedMode === 'date'
      ) setter = null;
    }
    value = setter ? formatDate(setter, format, i18n, formatType) : null;
    ...
}
```

If this is indeed expected behavior it should be optional IMO.

**Comment by mskocik** [comment]
Yes, it is intentional. Basically if you do not have `clearBtn` shown, there would be no way to deselect given date.

I agree, this behaviour could be optional, or at least "opt out"-able

**Comment by JackLeEmmerdeur** [comment]
Hey. Thanks a lot for the best svelte-native date-time-picker I've seen to date. I've only 2 small inconveniences:

One of them is exactly this issue here. I did not understand that I'm clearing the current date by clicking the selected date but rather thought it was a bug or my implementation fault until I saw your explanation @mskocik.

So the project's code seems to have been undergone heavy revamps since your commit [7a05535](https://github.com/mskocik/svelty-picker/commit/7a05535f62e405486d0af3ec07a542c1d4e3aa8f) and the clearToggle functionality hasn't survived, right? Would you consider implementing it again or open for a pull-request?
