### ISSUE TITLE
[Feature Request] Date Range Picker

### ISSUE THREAD

**Issue by risalfajar** [mskocik/svelty-picker#69]
Please consider adding a date range picker feature

![example](https://user-images.githubusercontent.com/28381124/196442858-3b249eb3-fc90-49b4-bc90-938bc604ce10.png)

**Comment by mskocik** [comment]
@CropWatchDevelopment of course you can work on it, but it would be great to discuss beforehand about the right approach of implementing it.

**Comment by shadowempire123** [comment]
Hi,
would also be nice to have a time start - time end for the range picker.
like https://svelte-datepicker.vercel.app/range-picker/with-time -> 
![image](https://user-images.githubusercontent.com/26248866/226284776-c2f4f252-7dca-4075-bdc2-b451c815d073.png)

I can not use svelte-datepicker.vercel.app because I can not configure, that the week starts with Monday... :-(
thx
