### ISSUE TITLE
Feature request: expose current picker mode

### ISSUE THREAD

**Issue by tbydza** [mskocik/svelty-picker#94]
Hello, 
I have similar problem to: [How to get value once when selector close?](https://github.com/mskocik/svelty-picker/issues/68)
There is possible solution to this. In on:change event handler I can filter out any unnecessary events based on the last or current mode (date, hours, minutes).
However there is no way of getting the mode from picker at the moment. 
Can you expose the current mode in some way please, for example by two-way props binding or slot props.
Thank you.

**Comment by mskocik** [comment]
Can you prepare PR for it?

**Comment by tbydza** [comment]
> Can you prepare PR for it?

https://github.com/mskocik/svelty-picker/pull/95

**Comment by mskocik** [comment]
Implemented in #95

**Comment by mskocik** [comment]
In v4 the whole 'autocommit' (called `autoclose` before) based logic has been reworked and this has become obsolete. Because there will always will be only _one_ change.

- for `date` picker - it's obvious on date selection
- for `datetime` or `time` picker - "change" is triggered by setting the _minutes_
- for `isRange` (daterange) picker - auto-commit logic is supported for `date` mode. For others, there are always buttons present to confirm or cancel selection.

I will keep this issue pinned until v4 release. But even today released version should be fine enough for typical use cases.
